Bug 26140: Introducing param to skip attribute refresh when valid
mapr/nfs-ganesha pull request #18
Opened 2018-07-10 11:48 UTC by vardhanh123

unitTested

10.10.103.38

NFS Ganesh

2018-07-11 02:45 UTC, SriKrishnachowdaryk commented on src/cache_inode/cache_inode_rdwr.c
> +			cache_inode_is_attrs_valid(entry));
Do not call this again. print CheckAttrs and check_valid_attrs instead.

2018-07-11 02:47 UTC, SriKrishnachowdaryk requested changes
Commit message should describe more. pls explain why we did what we did in this change.

Done

2018-07-11 10:17 UTC, satgs commented on src/cache_inode/cache_inode_rdwr.c
> +	    io_direction == CACHE_INODE_WRITE_PLUS) && !checkAttrs) {
We are modifying atime if checkattrs = true. That's undesirable.

2018-07-12 07:07 UTC, SriKrishnachowdaryk requested changes

2018-07-12 07:07 UTC, SriKrishnachowdaryk commented on src/cache_inode/cache_inode_rdwr.c
> +    if (canRefresh)
tabs

2018-07-12 08:55 UTC, SriKrishnachowdaryk requested changes

2018-07-12 08:55 UTC, SriKrishnachowdaryk commented on src/cache_inode/cache_inode_rdwr.c
> +		  status = cache_inode_refresh_attrs(entry);
tabs here.

2018-07-12 09:00 UTC, SriKrishnachowdaryk reviewed
LGTM

2018-07-12 09:23 UTC, satgs commented on src/support/nfs_read_conf.c
> +	CONF_ITEM_BOOL("Post_Write_Attrs_Update", true,
Default value should be false.

2018-07-12 09:25 UTC, satgs commented on src/cache_inode/cache_inode_rdwr.c
> +		if (canRefresh)
if (canRefresh) {
  status = refresh_attrs;
  if (status != SUCCESS) {
    goto out;
  }
}

2018-07-12 09:29 UTC, satgs reviewed
please fix the changes and check it in.

2018-07-12 09:43 UTC, merged